language: ruby
rvm:
- 2.3.3
cache: bundler

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="data.datacite.org";
      RACK_ENV="production";
      cp .env.master .env;
    else
      AWS_BUCKET="data.test.datacite.org";
      RACK_ENV="stage";
      cp .env.stage .env;
    fi

script:
  - bundle exec middleman build -e $RACK_ENV
  - bundle exec htmlproofer --http-status-ignore "999" --url-ignore "#" ./build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    all_branches: true
