version: '2'

services:
  cheetoh:
    env_file: .env
    image: datacite/cheetoh
    build: .
    ports:
      - "8070:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
  memcached:
    image: memcached:1.4.31
